openapi: 3.0.0
info:
  title: People API
  version: 1.0.0
  description: API for managing people counts
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /api/auth/login:
    post:
      summary: Login to get JWT token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /api/people:
    get:
      summary: Get all people
      responses:
        '200':
          description: Successful response
    post:
      summary: Create new people entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [man, woman, boy, girl]
                count:
                  type: integer
      responses:
        '201':
          description: Created
  /api/people/{id}:
    put:
      summary: Update people count
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                count:
                  type: integer
      responses:
        '200':
          description: Successful response