openapi: 3.0.0
info:
  title: People API
  version: 1.0.0
  description: API for managing people counts
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreatePeople:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            enum: [man, woman, boy, girl]
          count:
            type: integer
            minimum: 0
        required: ["type", "count"]
        additionalProperties: false
      minItems: 4
      uniqueItems: true
      contains:
        type: object
        properties:
          type:
            type: string
            enum: [man, woman, boy, girl]
        required: ["type"]
    People:
      type: object
      properties:
        type:
          type: string
          enum: [man, woman, boy, girl]
        count:
          type: integer
          minimum: 0
      required: ["type", "count"]
security:
  - bearerAuth: []
paths:
  /api/people:
    get:
      summary: Get all people
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalCount:
                    type: integer
                  people:
                    type: array
                    minItems: 4
                    uniqueItems: true
                    items:
                      $ref: "#/components/schemas/People"
                    contains:
                      $ref: "#/components/schemas/People"
    post:
      summary: Create new people entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                    enum: [man, woman, boy, girl]
                  count:
                    type: integer
              example:
                - type: man
                  count: 10
                - type: woman
                  count: 15
                - type: boy
                  count: 5
                - type: girl
                  count: 8
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: [man, woman, boy, girl]
                    count:
                      type: integer
